dist: bionic
sudo: false
language: java
jdk:
  - openjdk11
git:
  depth: 3

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: always
  slack:
    secure: "IeoyrbTPjPtopkmTFbcCzgy+9q8MMzhla9lXhZYdqsbn19KKe4UKNp0Cu0SY601ss586Lw4jsegvba6LFF3bi3j4aK0ZITtGJ4PYGvYByh3O7zi4Y0K2RUeYU1CfTIl18QBHcAIjQSmKLJPnyN9Y5Y4/4KhfWTqXy7tvkB36Oys="

cache:
  directories:
    - "$HOME/.m2"

services:
  - docker

before_install:
  - ./core/bin/run-mongo-container.sh
  - ./core/bin/before-deploy.sh

install: true

before_script:
  - RESTHEART_VERSION=$(./project-version.sh 2>/dev/null)
  - export RESTHEART_VERSION
  - echo "RESTHEART_VERSION=${RESTHEART_VERSION}"

script:
  - docker ps
  - ./core/bin/maven-deploy.sh

# Deploy to Github
deploy:
  provider: releases
  api_key:
    secure: EEGZ5uRn23QqhPqiENRZxBkuDw+qyl23ELUr0HHltI/DK+UIsFQrQydZbtl6VIPTzE8O3EOy/PhzTk2zXlh5cfi+THkIAzpNzW93CAUNFMknUV/cDsrgRSKwEXlF1LJ1WqerM8g4pKvyfyJTOIkFwir/1bIZ/ww+8zIqw6+SBlo=
  file_glob: true
  file:
    - "target/restheart-*.tar.gz"
    - "target/restheart-*.zip"
    - "target/restheart.jar"
  skip_cleanup: true
  on:
    tags: true
    condition: $MAVEN_DEPLOY = true

env:
  matrix:
    - MONGO=4.2 REPLICASET=true KARATE_OPS="" MAVEN_DEPLOY=true
    - MONGO=4.0 REPLICASET=true KARATE_OPS=""
    - MONGO=3.6 REPLICASET=false KARATE_OPS="--tags ~@requires-mongodb-4 ~@requires-replica-set"
    - MONGO=3.4 REPLICASET=false KARATE_OPS="--tags ~@requires-mongodb-4 ~@requires-mongodb-3.6 ~@requires-replica-set"
  global:
    -  # GITHUB_TOKEN
    - secure: "P+eIZffIwlYApsZ+i87jQ0/SXTNwWpAiq5QcjJPLSlUxFrBsTUbI2nvW1NWJNb9+lZS08bTpEtm5NC1bIKW8zBLVSdidr0m7ogSa+BdvclXvQ4Zu5YEJETJ6+IP5EAn03NSfbfUrWz/mtlplSCK6Mr1dRVFT/7ictQMvvkFoqok="
    -  # GPG_KEY_NAME
    - secure: "TpW3POqtLLgSjYq0eGc03fk90AlkoqYieNht8c1AE/vgP442G1y9jkKk81AQulGHmpGZYQ3slhtn754jwAS2uzcHb4DtjIsbZvum/Ipbebgmi5Gi2sVcsWXPaEPoctzf/+tuKLz1psjuZzT3m1K2AaqvhUlKwy7oAgZt0X78axM="
    -  # GPG_PASSPHRASE
    - secure: "U5su51eqq16En2sVYwCT8oseHfXWLO5dLjDvKpDefg+wLXF9y1E8Ckic0m2Rzq4mQdJMyrrQk+ZLu+LSgQC3kfHCrjDJ1Qv+olnPuuGPVZqlc+bQRgwBkyUWOXts+8t8JTF3swEz4kVV9mGTeQiuchjBlySaPSSNQStEXoI7+dg="
