language: java
jdk:
- openjdk11
git:
  depth: 3
sudo: false
services:
- docker
notifications:
  email:
    recipients:
    - info@softinstigate.com
    on_success: change
    on_failure: always
  slack: s-i:fgs1E6lggHh7JNFFqGMsWTPz
cache:
  directories:
  - "$HOME/.m2"
install: true
script: mvn clean deploy --settings settings.xml -Dmaven.test.skip=true;
after_success: "./bin/push.sh"
deploy:
  provider: releases
  draft: true
  api_key:
    secure: MOhMMkM3rmUealV2OPnr+4zE4SD7tAjvebUK+J3wfnRCJOIh8Yfib3ug+gu/u4XhrBocRBRPSc7cOPvAVimEbVfptyK+s8JzeFr2XtV9k1aTfCgACQu804M4l3XTSDylSke4Fj6RRM7lwwToJEyJI1gxp12hYnWxmfmRN8sG3fvs9AsqBj8OCFT5sYGwOdpTDGcyf1STQv1X5ToNvSxpRURzyk7BoK1mVVIOlzJvzeHKS8PUCuOzHurI4ovTxonUSjTCKoRMh1vvh2KnUoDwS6vBe+SypmfdQzoK048WJVCha3WJluyZ9s4Z5lWD0ibM7wn4P41Xke0mlKuqswdnrx0TMW86JicK78tW/lU/GwOluN6y0uGnPrgdR8KWsXAbB79Z0nMGrxKFrrYRryjzpnsQWfVeK569VBM3urX/P+KjYM9iLTFluR1By19jRIsIUuDUXKieVSARyb/aZ7qrHXTs8Dzr0CghS0nx2RBq4vH+vZADVslfkN9cSaWa4vas42sP6AbKOpeMEkW51bBxmZFqe6FHPt5QBtVpIfA6I2stED2C+QaDJzmF3i3vDZKMwRXEor6rrmEyJsCWTg5zAFg/KOIj+OAZCQwdIGTA0yQQ47Ns/h0zpqRod0rJouxgn4co2zyOmM8LPOW3UD0tAPxXXyv0LObepjmT3lJVHDw=
  file: 
  - "target/uiam.jar"
  skip_cleanup: true
  on:
    tags: true
