dist: xenial
sudo: false
language: java
jdk:
  - openjdk11
git:
  depth: 10

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: always
  slack:
    secure: "IeoyrbTPjPtopkmTFbcCzgy+9q8MMzhla9lXhZYdqsbn19KKe4UKNp0Cu0SY601ss586Lw4jsegvba6LFF3bi3j4aK0ZITtGJ4PYGvYByh3O7zi4Y0K2RUeYU1CfTIl18QBHcAIjQSmKLJPnyN9Y5Y4/4KhfWTqXy7tvkB36Oys="

cache:
  directories:
    - "$HOME/.m2"

services:
  - docker

before_install:
  - ./bin/run-mongo-container.sh

install: true

before_script:
  - git submodule update --init --recursive

script:
  - docker ps
  - ./bin/build.sh

env:
  matrix:
    - MONGO=4.0 REPLICASET=true KARATE_OPS=""
    - MONGO=3.6 REPLICASET=false KARATE_OPS="--tags ~@requires-mongodb-4 ~@requires-replica-set"
    - MONGO=3.4 REPLICASET=false KARATE_OPS="--tags ~@requires-mongodb-4 ~@requires-mongodb-3.6 ~@requires-replica-set"
  global:
    - secure: "rlLQCDykTqV7/EC+kTCw5JpYbuZwk0Neq5q1kRQ6hjcUYRdgjPJretVg+1e5+GcGOH4/Z/aOGdQrk1HtPW6tE+ePIUDAUwuLX2+6AUt2FqIqumYoJxYR7rsw+THkjiPaopB7qmWOUJ1vec7QCEiaGexYcjs3j6mv//SbnUksY2w="
    - secure: "t4tS+6EAC9nuE9SOKMfooux34usyPY2oBt0/737A2o9y3LXgy/jt0hyx09W4Gc1ZHq8QYoEiwHU40rlo2KWcxPKK/e4U/dZ1ne5OBJLKt5dhGr/PwaO0rVa7039zgQRn1VN+ayx92AfQCZMyA7iTrVDrM/2lxvDww0UYyZmViaA="
    - secure: "NJiw/JRqiwYkEx2eisu5yllgX6oKJwhV60SldnlpnHqWzOaqXoqsKLOiP18cBPeLT6BuVYT9Z0PyaI9+2bPzt2IUC6vKuhimPYA0IRqoDfAcdSKa/Q1LcbLdbX+T941IE0iPlVesh3iFf41Cc5BM5ND2fu/yRlAHOcJFTdSqGAs="
    -  # GITHUB_TOKEN
    - secure: "P+eIZffIwlYApsZ+i87jQ0/SXTNwWpAiq5QcjJPLSlUxFrBsTUbI2nvW1NWJNb9+lZS08bTpEtm5NC1bIKW8zBLVSdidr0m7ogSa+BdvclXvQ4Zu5YEJETJ6+IP5EAn03NSfbfUrWz/mtlplSCK6Mr1dRVFT/7ictQMvvkFoqok="
    -  # GPG_KEY_NAME
    - secure: "TpW3POqtLLgSjYq0eGc03fk90AlkoqYieNht8c1AE/vgP442G1y9jkKk81AQulGHmpGZYQ3slhtn754jwAS2uzcHb4DtjIsbZvum/Ipbebgmi5Gi2sVcsWXPaEPoctzf/+tuKLz1psjuZzT3m1K2AaqvhUlKwy7oAgZt0X78axM="
    -  # GPG_PASSPHRASE
    - secure: "U5su51eqq16En2sVYwCT8oseHfXWLO5dLjDvKpDefg+wLXF9y1E8Ckic0m2Rzq4mQdJMyrrQk+ZLu+LSgQC3kfHCrjDJ1Qv+olnPuuGPVZqlc+bQRgwBkyUWOXts+8t8JTF3swEz4kVV9mGTeQiuchjBlySaPSSNQStEXoI7+dg="
