## RESTHeart simple security configuration file.

##Â look at undertow documentation for information about predictates syntax 
## http://undertow.io/documentation/core/predicates-attributes-handlers.html

## the special role $unauthenticated allows to give permissions without requiring authentication


---
users:
    - userid: user
      password: changeit
      roles: [users]
          
    - userid: user2
      password: changeit
      roles: [users]
    
    - userid: admin
      password: changeit
      roles: [users, admins]
      
permissions:
    - role: admins
      predicate: path-prefix[path="/"]
      
    - role: $unauthenticated
      predicate: path-prefix[path="/publicdb/"] and method[value="GET"]
      
    - role: users
      predicate: regex[pattern="/.*/.*", value="%R", full-match=true] and method[value="GET"]
      
    - role: users
      predicate: path-prefix[path="/publicdb/{username}/"]