## configuration file for RESTHeart integration  test suite
---
users:
    - userid: user1
      password: changeit
      roles: [poweruser]

    - userid: user2
      password: changeit
      roles: [user]

    - userid: admin
      password: changeit
      roles: [user, admin]

permissions:
  - role: admin
    predicate: path-prefix[path="/"]

  - role: $unauthenticated
    predicate: path-prefix[path="/testdb/refcoll1"] and method[value="GET"]

  - role: poweruser
    predicate: path-prefix[path="/testdb"] and method[value="GET"]

  - role: poweruser
    predicate: path-prefix[path="/testmytmpdb"]

  - role: user
    predicate: path-prefix[path="/testdb/refcoll2"] and method[value="GET"]

  - role: user
    predicate: path[path="/testdb/refcoll2"] and method[value="GET"]

  - role: user
    predicate: (path[path="/testtmpdb2"] or path[path="/testtmpdb3"]) and method[value="PUT"]

  # This to check the path-template predicate
  - role: user
    predicate: path-template[value="/testtmpdb2/{username}"] and equals[%u, "${username}"]

  # This to check the regex predicate
  - role: user
    predicate: regex[pattern="/testtmpdb3/(.*?)", value="%R", full-match=true] and equals[%u, "${1}"]
